import Head from "next/head";
import { Inter } from "@next/font/google";
import Script from "next/script";
const inter = Inter({ subsets: ["latin"] });
type LayoutProps = {
  children: React.ReactNode;
};
export default function Layout({
  children,
}: LayoutProps) {
  return (
    <>
      <Script src="https://code.iconify.design/iconify-icon/1.0.2/iconify-icon.min.js" />
      <Head>
        <title>@furkansahins34</title>
        <meta name="description" content="Generated by @furkansahins34" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-lg min-w-[300px] md:rounded-xl lg:border md:shadow-lg lg:mt-4 min-h-screen mb-4 mx-auto">
        <div className="header p-4">
          <div className="flex justify-between">
            <span className="hi flex flex-col gap-1 text-2xl">
              <span className="font-bold">Hi Furkan S.</span>
              <span className="text-sm text-gray-600">10 Tasks pending</span>
            </span>

            <span className="avatar text-3xl mt-2 mr-2 bg-slate-50 shadow-md rounded-full p-2 leading-8 text-center">
              👨🏻‍💻
            </span>
          </div>
        </div>

        {children}
      </main>
    </>
  );
}
