import Head from "next/head";
import { Inter } from "@next/font/google";
import Script from "next/script";
const inter = Inter({ subsets: ["latin"] });
type LayoutProps = {
  children: React.ReactNode;
};
export default function Layout({ children }: LayoutProps) {
  return (
    <>
      <Script src="https://code.iconify.design/iconify-icon/1.0.2/iconify-icon.min.js" />
      <Head>
        <title>@furkansahins34</title>
        <meta name="description" content="Generated by @furkansahins34" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-lg min-w-[300px] md:rounded-xl lg:border md:shadow-lg lg:mt-4 min-h-screen mb-4 mx-auto">
        <div className="header p-4">
          <div className="flex justify-between">
            <span className="hi flex flex-col gap-1 text-2xl">
              <span className="font-bold">Hi Furkan S.</span>
              <span className="text-sm text-gray-600">10 Tasks pending</span>
            </span>

            <span className="avatar text-3xl mt-2 mr-2 bg-slate-50 shadow-md rounded-full p-2 leading-8 text-center">
              👨🏻‍💻
            </span>
          </div>
        </div>

        {children}

        <a 
        target="{_blank}"
        href="https://github.com/swoorr/react-tailwind-next-mobile-ui-design"
        className="cursor-pointer fixed bottom-7 left-7 !index-100 m-0 bg-indigo-600 p-2 px-4 rounded text-sm text-white hover:bg-slate-500">
        <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><path fill="#eee" d="M12 2A10 10 0 0 0 2 12c0 4.42 2.87 8.17 6.84 9.5c.5.08.66-.23.66-.5v-1.69c-2.77.6-3.36-1.34-3.36-1.34c-.46-1.16-1.11-1.47-1.11-1.47c-.91-.62.07-.6.07-.6c1 .07 1.53 1.03 1.53 1.03c.87 1.52 2.34 1.07 2.91.83c.09-.65.35-1.09.63-1.34c-2.22-.25-4.55-1.11-4.55-4.92c0-1.11.38-2 1.03-2.71c-.1-.25-.45-1.29.1-2.64c0 0 .84-.27 2.75 1.02c.79-.22 1.65-.33 2.5-.33c.85 0 1.71.11 2.5.33c1.91-1.29 2.75-1.02 2.75-1.02c.55 1.35.2 2.39.1 2.64c.65.71 1.03 1.6 1.03 2.71c0 3.82-2.34 4.66-4.57 4.91c.36.31.69.92.69 1.85V21c0 .27.16.59.67.5C19.14 20.16 22 16.42 22 12A10 10 0 0 0 12 2Z"/></svg>

        </a>
      </main>
    </>
  );
}
